### ISSUE TITLE
PyFR: Incorrect 'backend' property sent to taskflow

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#303]
If I switch to a different cluster and select and different backend (openmp), the backend sent is 'cuda', the backend of the previous cluster ...

**Comment by TristanWright** [comment]
fixed in #315

**Comment by TristanWright** [comment]
I don't see this anymore either?

**Comment by cjh1** [comment]
Yes, this is still happening. I have two clusters one that is using cuda the other is using openmp. If I switch to the openmp one it still sends the backend as cuda.

**Comment by cjh1** [comment]
This seems to be fixed
